from enum import StrEnum


class CallStateName(StrEnum):
    """Tên các trạng thái điều phối hội thoại của Callbot."""

    AWAITING_IDENTITY = "AWAITING_IDENTITY"
    AWAITING_INTENT = "AWAITING_INTENT"
    AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION"
    OFFERING_SLOTS = "OFFERING_SLOTS"
    TRANSFER_REQUIRED = "TRANSFER_REQUIRED"
    CLOSING = "CLOSING"
    ENDED = "ENDED"


class CallActionName(StrEnum):
    """Actions that can be requested from the deterministic Callbot core."""

    START_CALL = "START_CALL"
    COLLECT_IDENTITY = "COLLECT_IDENTITY"
    VERIFY_IDENTITY = "VERIFY_IDENTITY"
    HANDLE_SILENCE = "HANDLE_SILENCE"
    TRANSFER_TO_STAFF = "TRANSFER_TO_STAFF"
    END_CALL = "END_CALL"
    READ_APPOINTMENT = "READ_APPOINTMENT"
    DISCLOSE_APPOINTMENT = "DISCLOSE_APPOINTMENT"
    CONFIRM_APPOINTMENT = "CONFIRM_APPOINTMENT"
    CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT"
    GET_SLOTS = "GET_SLOTS"
    OFFER_SLOTS = "OFFER_SLOTS"
    RESCHEDULE_APPOINTMENT = "RESCHEDULE_APPOINTMENT"
    BOOK_APPOINTMENT = "BOOK_APPOINTMENT"
